/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VVideos: typeof import('./components/v-videos/v-videos.vue')['default']
    'v-videos': typeof import('./components/v-videos/v-videos.vue')['default']
  }
}
